server:
  port: 80
eureka:
  client:
    registry-with-eureka: false
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

ribbon:
  #建立连接时间
  ReadTimeout: 5000
  #读取资源时间
  ConnectTimeout: 5000
logging:
  level:
    #feign日志以什么级别监控，哪个接口
    com.qzh.springcloud.service.PaymentFeignService: debug
