server:
  port: 80

spring:
  application:
    name: cloud-feignOrder-service

eureka:
  client:
    registry-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: feignOrder80
    #显示ip地址
    prefer-ip-address: true
ribbon:
  #建立连接时间
  ReadTimeout: 5000
  #读取资源时间
  ConnectTimeout: 5000
logging:
  level:
    #feign日志以什么级别监控，哪个接口
    com.qzh.springcloud.service.PaymentFeignService: debug
